#  new action
owner: andsouzam # Your GitHub organization or username, where this repository lives
repo: StatusPage # The name of this repository

sites:
  - name: SGR
    url: https://sgr.hinova.com.br/sgr/sgrv3/3569/dashboard/graficos
    expectedStatusCodes: 
     - 200
  - name: SystemSatX
    url: https://tracking.systemsatx.com.br/
    expectedStatusCodes: 
     - 200
  - name: Getrack
    url: https://sis.getrak.com/pontotrack/msumario/index
    expectedStatusCodes: 
     - 200
  - name: Moskit
    url: https://app.moskitcrm.com/login
    expectedStatusCodes: 
     - 200
  - name: D4Sign
    url: https://secure.d4sign.com.br/login.html?r=/?
    expectedStatusCodes: 
     - 200
assignees: # Users to assign downtime issues (optional)
  - andsouzam

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: servicestatus.pontotrack.com
  baseUrl: /StatusPage
  logoUrl: https://customerm365011-my.sharepoint.com/personal/andersonmiranda_pontotrack_com/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fandersonmiranda%5Fpontotrack%5Fcom%2FDocuments%2Flogo%20ponto%20track%5FFUNDO%20ESCURO%2Epng&parent=%2Fpersonal%2Fandersonmiranda%5Fpontotrack%5Fcom%2FDocuments&ga=1
  name: Serviços PontoTrack
  introTitle: "Esta é a página de status dos nossos serviços."
  introMessage: "Aqui você pode acompanhar a disponibilidade em tempo real."
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
