# new action
owner: andsouzam # Your GitHub organization or username, where this repository lives
repo: StatusPage # The name of this repository

sites:
  - name: SGR
    url: https://sgr.hinova.com.br/sgr/sgrv3/3569/dashboard/graficos
  - name: SystemSatX
    url: https://tracking.systemsatx.com.br/
  - name: Getrack
    url: https://sis.getrak.com/pontotrack/msumario/index
  - name: Moskit
    url: https://app.moskitcrm.com/login
  - name: D4Sign
    url: https://secure.d4sign.com.br/login.html?r=/?

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: servicestatus.pontotrack.com
  baseUrl: /StatusPage # where "repo" is your repository name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Serviços PontoTrack
  introTitle: "Esta é a página de status dos nossos serviços."
  introMessage: "Aqui você pode acompanhar a disponibilidade em tempo real."
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
